=== AntoineCanda/M1_S2/LABD/DS1/rendu/dtd3.dtd
<!-- DTD created at Sat Feb 18 11:42:30 CET 2017 with EditiX XML Editor (http://www.editix.com). Please insert an encoding attribute header for converting any DTD  -->


<!ELEMENT A (B*, D*,F?)>

<!ELEMENT B (C*) >

<!ELEMENT D (F*) >
<!ELEMENT  C (#PCDATA)>
<!ELEMENT  F (#PCDATA)>

=== AntoineCanda/M1_S2/LABD/DS1/rendu/a2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XML document created with EditiX XML Editor (http://www.editix.com) at Sat Feb 18 11:35:22 CET 2017 -->


<!DOCTYPE A SYSTEM "dtd3.dtd">
<A>
	<B>
		<C>
			4
		</C>
	</B>
	<D>
		<F>
			5
		</F>
		<F>
			6
		</F>
	</D>
	<D />
	<F>
		7
	</F>
</A>
